title: Elian Tiudic # your name (or website title) here
logo: "/images/personal pic.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Hi! I'm Elian</b>.
  I'm a second year computer science student at Brooklyn College.
  <br><br>
  I'm familiar with Java, C++, and Python. On the right there are some of my projects.
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
